version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing-page-web
    volumes:
      - ".:/app"
    env_file:
      - .env
    ports:
      - "81:80"
    tty: true